export const ChannelText = {
  join: "Join",
  addChannel: "Add a channel",
  channelPlaceholder: "e.g plan-budget",
  createChannel: "Create Channel",
  invitePeople: "Invite people to ",
  inviteDescription: "Use this code below to invite people to join ",
  newCode: "New Code",
  close: "Close",
  newCodeSuccess: "New code generated successfully",
  newCodeError: "Failed to regenerate new code",
  backHome: "Back to home",
  joinSuccess: "Successfully joined the workspace",
  joinError: "Failed to join the workspace",
};
